name: Django Workflow

on:
  push:
    branches: [ "main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12]
    
    steps:

    - name: Checkout the latest code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Django Migration Checker
      uses: hardcoretech/django-migration-checker-action@v2
      with:
        app-path: .
        docker-image-tag: latest
