name: Django Workflow

on:
  push:
    branches: [ "main", "feature/setup"]
  pull_request:
    branches: ["main", "feature/setup"]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12, 3.13]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - uses: actions/action-setup-postgres@v6
      with:
        username: postgres
        password: root
        database: todo_system
        port: 5432
        postgres-version: "16"
        ssl: "on"
      id: postgres

      
    - name: Install Dependencies
      run: |
        python -m pip install poetry==1.8.2
        poetry install 
        echo "Dependencies installed successfully"
        
    - name: Make Migrations
      run: |
        python todo/manage.py makemigrations
        python todo/manage.py migrate
        echo "Migrations completed successfully"
      
    # - name: Run Tests
    #   run: |
    #     python manage.py test
